[package]
name = "gregg_anni_interpreter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
linfa = "0.6.1"
linfa-trees = "0.6.1"
ndarray = "0.15.6"
csv = "1.1.6"
image = "0.24.5"